//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Cosmos : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 joystick
        {
            get
            {
                return SteamVR_Actions.cosmos_joystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_touch
        {
            get
            {
                return SteamVR_Actions.cosmos_joystick_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_click
        {
            get
            {
                return SteamVR_Actions.cosmos_joystick_click;
            }
        }
        
        public virtual SteamVR_Action_Single trigger
        {
            get
            {
                return SteamVR_Actions.cosmos_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_touch
        {
            get
            {
                return SteamVR_Actions.cosmos_trigger_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_click
        {
            get
            {
                return SteamVR_Actions.cosmos_trigger_click;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_click
        {
            get
            {
                return SteamVR_Actions.cosmos_grip_click;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu
        {
            get
            {
                return SteamVR_Actions.cosmos_menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttonAX
        {
            get
            {
                return SteamVR_Actions.cosmos_buttonAX;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttonBY
        {
            get
            {
                return SteamVR_Actions.cosmos_buttonBY;
            }
        }
        
        public virtual SteamVR_Action_Boolean bumper
        {
            get
            {
                return SteamVR_Actions.cosmos_bumper;
            }
        }
        
        public virtual SteamVR_Action_Skeleton left_hand
        {
            get
            {
                return SteamVR_Actions.cosmos_left_hand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton right_hand
        {
            get
            {
                return SteamVR_Actions.cosmos_right_hand;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.cosmos_pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration haptic
        {
            get
            {
                return SteamVR_Actions.cosmos_haptic;
            }
        }
    }
}
