//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_PicoNeo : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 thumbstick
        {
            get
            {
                return SteamVR_Actions.picoNeo_thumbstick;
            }
        }
        
        public virtual SteamVR_Action_Boolean thumbstick_touch
        {
            get
            {
                return SteamVR_Actions.picoNeo_thumbstick_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean thumbstick_click
        {
            get
            {
                return SteamVR_Actions.picoNeo_thumbstick_click;
            }
        }
        
        public virtual SteamVR_Action_Single trigger
        {
            get
            {
                return SteamVR_Actions.picoNeo_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_click
        {
            get
            {
                return SteamVR_Actions.picoNeo_trigger_click;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_click
        {
            get
            {
                return SteamVR_Actions.picoNeo_grip_click;
            }
        }
        
        public virtual SteamVR_Action_Boolean app
        {
            get
            {
                return SteamVR_Actions.picoNeo_app;
            }
        }
        
        public virtual SteamVR_Action_Boolean system
        {
            get
            {
                return SteamVR_Actions.picoNeo_system;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttonYB
        {
            get
            {
                return SteamVR_Actions.picoNeo_buttonYB;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttonXA
        {
            get
            {
                return SteamVR_Actions.picoNeo_buttonXA;
            }
        }
        
        public virtual SteamVR_Action_Skeleton left_hand
        {
            get
            {
                return SteamVR_Actions.picoNeo_left_hand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton right_hand
        {
            get
            {
                return SteamVR_Actions.picoNeo_right_hand;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.picoNeo_pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration haptic
        {
            get
            {
                return SteamVR_Actions.picoNeo_haptic;
            }
        }
    }
}
