//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Generic : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.generic_Pose;
            }
        }
        
        public virtual SteamVR_Action_Single Strength
        {
            get
            {
                return SteamVR_Actions.generic_Strength;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Axis
        {
            get
            {
                return SteamVR_Actions.generic_Axis;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchingStrength
        {
            get
            {
                return SteamVR_Actions.generic_TouchingStrength;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchingAxis
        {
            get
            {
                return SteamVR_Actions.generic_TouchingAxis;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActionPrimary
        {
            get
            {
                return SteamVR_Actions.generic_ActionPrimary;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActionSecondary
        {
            get
            {
                return SteamVR_Actions.generic_ActionSecondary;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActionGrab
        {
            get
            {
                return SteamVR_Actions.generic_ActionGrab;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActionMenu
        {
            get
            {
                return SteamVR_Actions.generic_ActionMenu;
            }
        }
        
        public virtual SteamVR_Action_Skeleton LeftHand
        {
            get
            {
                return SteamVR_Actions.generic_LeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton RightHand
        {
            get
            {
                return SteamVR_Actions.generic_RightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean UserPresent
        {
            get
            {
                return SteamVR_Actions.generic_UserPresent;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.generic_Haptic;
            }
        }
    }
}
