//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Vive : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean trigger_hair
        {
            get
            {
                return SteamVR_Actions.vive_trigger_hair;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_click
        {
            get
            {
                return SteamVR_Actions.vive_trigger_click;
            }
        }
        
        public virtual SteamVR_Action_Single trigger
        {
            get
            {
                return SteamVR_Actions.vive_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean touchpad_touch
        {
            get
            {
                return SteamVR_Actions.vive_touchpad_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean touchpad_click
        {
            get
            {
                return SteamVR_Actions.vive_touchpad_click;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchpad
        {
            get
            {
                return SteamVR_Actions.vive_touchpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip
        {
            get
            {
                return SteamVR_Actions.vive_grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean app
        {
            get
            {
                return SteamVR_Actions.vive_app;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.vive_pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton left_hand
        {
            get
            {
                return SteamVR_Actions.vive_left_hand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton right_hand
        {
            get
            {
                return SteamVR_Actions.vive_right_hand;
            }
        }
        
        public virtual SteamVR_Action_Vibration haptic
        {
            get
            {
                return SteamVR_Actions.vive_haptic;
            }
        }
    }
}
