//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_OculusTouch : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean start
        {
            get
            {
                return SteamVR_Actions.oculusTouch_start;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_YB
        {
            get
            {
                return SteamVR_Actions.oculusTouch_button_YB;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_XA
        {
            get
            {
                return SteamVR_Actions.oculusTouch_button_XA;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_YB_touch
        {
            get
            {
                return SteamVR_Actions.oculusTouch_button_YB_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_XA_touch
        {
            get
            {
                return SteamVR_Actions.oculusTouch_button_XA_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean thumbrest_touch
        {
            get
            {
                return SteamVR_Actions.oculusTouch_thumbrest_touch;
            }
        }
        
        public virtual SteamVR_Action_Single grip
        {
            get
            {
                return SteamVR_Actions.oculusTouch_grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_click
        {
            get
            {
                return SteamVR_Actions.oculusTouch_grip_click;
            }
        }
        
        public virtual SteamVR_Action_Vector2 joystick
        {
            get
            {
                return SteamVR_Actions.oculusTouch_joystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_touch
        {
            get
            {
                return SteamVR_Actions.oculusTouch_joystick_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_click
        {
            get
            {
                return SteamVR_Actions.oculusTouch_joystick_click;
            }
        }
        
        public virtual SteamVR_Action_Single trigger
        {
            get
            {
                return SteamVR_Actions.oculusTouch_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_touch
        {
            get
            {
                return SteamVR_Actions.oculusTouch_trigger_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_click
        {
            get
            {
                return SteamVR_Actions.oculusTouch_trigger_click;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.oculusTouch_pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton left_hand
        {
            get
            {
                return SteamVR_Actions.oculusTouch_left_hand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton right_hand
        {
            get
            {
                return SteamVR_Actions.oculusTouch_right_hand;
            }
        }
        
        public virtual SteamVR_Action_Vibration haptic
        {
            get
            {
                return SteamVR_Actions.oculusTouch_haptic;
            }
        }
    }
}
