//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Knuckles : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single grip
        {
            get
            {
                return SteamVR_Actions.knuckles_grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_touch
        {
            get
            {
                return SteamVR_Actions.knuckles_grip_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_A
        {
            get
            {
                return SteamVR_Actions.knuckles_button_A;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_B
        {
            get
            {
                return SteamVR_Actions.knuckles_button_B;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_A_touch
        {
            get
            {
                return SteamVR_Actions.knuckles_button_A_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean button_B_touch
        {
            get
            {
                return SteamVR_Actions.knuckles_button_B_touch;
            }
        }
        
        public virtual SteamVR_Action_Single trigger
        {
            get
            {
                return SteamVR_Actions.knuckles_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_touch
        {
            get
            {
                return SteamVR_Actions.knuckles_trigger_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_click
        {
            get
            {
                return SteamVR_Actions.knuckles_trigger_click;
            }
        }
        
        public virtual SteamVR_Action_Vector2 joystick
        {
            get
            {
                return SteamVR_Actions.knuckles_joystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_touch
        {
            get
            {
                return SteamVR_Actions.knuckles_joystick_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_click
        {
            get
            {
                return SteamVR_Actions.knuckles_joystick_click;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchpad
        {
            get
            {
                return SteamVR_Actions.knuckles_touchpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean touchpad_touch
        {
            get
            {
                return SteamVR_Actions.knuckles_touchpad_touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean touchpad_press
        {
            get
            {
                return SteamVR_Actions.knuckles_touchpad_press;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.knuckles_pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_click
        {
            get
            {
                return SteamVR_Actions.knuckles_grip_click;
            }
        }
        
        public virtual SteamVR_Action_Single touchpad_force
        {
            get
            {
                return SteamVR_Actions.knuckles_touchpad_force;
            }
        }
        
        public virtual SteamVR_Action_Skeleton left_hand
        {
            get
            {
                return SteamVR_Actions.knuckles_left_hand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton right_hand
        {
            get
            {
                return SteamVR_Actions.knuckles_right_hand;
            }
        }
        
        public virtual SteamVR_Action_Vibration haptic
        {
            get
            {
                return SteamVR_Actions.knuckles_haptic;
            }
        }
    }
}
